name: Build & Test (PHP 8.2, 8.3, 8.4)

on:
    pull_request:
        branches:
            - 'main'
        types: [ opened, synchronize, reopened, ready_for_review ]
    push:
        branches:
            - 'main'

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                version: [  '8.2', '8.3', '8.4' ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                if: success()

            -   name: Setup PHP with coverage driver
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.version }}
                    coverage: pcov

            -   name: Setup
                if: success()
                run: |
                    composer install --no-interaction

            -   name: PHPUnit tests with coverage
                if: success()
                run: |
                    composer test-coverage

            -   name: upload coverage to codecov.io
                if: success() && matrix.version == '8.2'
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: ./coverage.xml
